downgrade git-url-parse to test if it fixes typescript issue (when using this lib)
error TS2688: Cannot find type definition file for 'parse-path'.
  The file is in the program because:
    Entry point for implicit type library 'parse-path'